#!/usr/bin/env python3
"""
Build markdown documentation from papers_record.xlsx.
Generates individual .md files + index under markdown/ directory.

Usage:
  python3 build_markdown.py
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from openpyxl import load_workbook

BASE_DIR = Path(__file__).resolve().parent
EXCEL_PATH = BASE_DIR / "papers_record.xlsx"
MARKDOWN_DIR = BASE_DIR / "markdown"
DELETED_IDS_PATH = BASE_DIR / "deleted_ids.txt"


def load_deleted_ids() -> set[str]:
    if not DELETED_IDS_PATH.exists():
        return set()
    ids = set()
    with open(DELETED_IDS_PATH, encoding="utf-8") as f:
        for line in f:
            sid = line.strip()
            if sid and not sid.startswith("#"):
                ids.add(sid)
    return ids


def load_rows() -> list[dict]:
    wb = load_workbook(EXCEL_PATH, read_only=True)
    ws = wb["Papers"]
    header_row = next(ws.iter_rows(min_row=1, max_row=1, values_only=True))
    headers = [str(h) if h is not None else "" for h in header_row]
    idx = {name: i for i, name in enumerate(headers)}

    required = ["arxiv_id", "title", "authors", "published_date",
                "categories", "abstract", "summary_cn", "pdf_filename", "crawled_date"]
    rows = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        paper = {col: str(row[idx[col]]) if row[idx[col]] is not None else ""
                 for col in required}
        if not paper["arxiv_id"]:
            continue
        paper["pdf_url"] = f"https://arxiv.org/pdf/{paper['arxiv_id']}"
        paper["abs_url"] = f"https://arxiv.org/abs/{paper['arxiv_id']}"
        rows.append(paper)

    rows.sort(key=lambda x: (x["crawled_date"], x["published_date"]), reverse=True)
    return rows


def sanitize_filename(s: str) -> str:
    """Make a safe filename from a title."""
    keep = []
    for ch in s:
        if ch.isalnum() or ch in " _-":
            keep.append(ch)
        elif ch in "/\\:*?\"<>|":
            keep.append("-")
    name = "".join(keep).strip().replace(" ", "_")[:80]
    return name or "paper"


def paper_markdown(p: dict) -> str:
    """Generate markdown content for a single paper."""
    return f"""# {p['title']}

**arXiv ID**: [{p['arxiv_id']}]({p['abs_url']})  
**Authors**: {p['authors']}  
**Published**: {p['published_date']} | **Crawled**: {p['crawled_date']}  
**Categories**: {p['categories']}  
**PDF**: [{p['pdf_filename']}]({p['pdf_url']})

---

## 中文摘要

{p['summary_cn'] or '（暂未提供）'}

---

## Abstract

{p['abstract'] or '（暂未提供）'}

---

> Auto-generated by hermes-arxiv-agent on {date.today().isoformat()}
"""


def main():
    MARKDOWN_DIR.mkdir(parents=True, exist_ok=True)

    all_papers = load_rows()
    deleted_ids = load_deleted_ids()
    papers = [p for p in all_papers if p["arxiv_id"] not in deleted_ids]

    # Generate individual markdown files
    md_links = []
    for p in papers:
        fname = f"{p['arxiv_id']}-{sanitize_filename(p['title'])}.md"
        filepath = MARKDOWN_DIR / fname
        filepath.write_text(paper_markdown(p), encoding="utf-8")
        summary_preview = (p["summary_cn"] or p["abstract"] or "")[:80]
        md_links.append(f"- [{p['arxiv_id']}]({fname}) — {p['title'][:80]} | {summary_preview}")

    # Generate index
    index_content = f"""# Agent Memory 论文 Markdown 文档

> Auto-generated: {date.today().isoformat()} | Papers: {len(papers)} | Excluded (deleted): {len(deleted_ids)}

---

{"".join(md_links)}

---

[在线查看](https://peng-yinghao.github.io/hermes-arxiv-agent/)
"""
    (MARKDOWN_DIR / "README.md").write_text(index_content, encoding="utf-8")

    print(f"[OK] Generated {len(papers)} markdown files under {MARKDOWN_DIR}")
    print(f"[OK] Index: {MARKDOWN_DIR / 'README.md'}")


if __name__ == "__main__":
    main()
