#!/usr/bin/env python3
"""
Download full-paper Markdown from arXiv HTML using arxiv2md.
Stores under markdown_full/ directory, one .md per paper.
Skips papers where HTML version is not available (older papers).

Usage:
  python3 build_markdown_full.py          # download all
  python3 build_markdown_full.py <id>     # download single paper
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import time
from datetime import date
from pathlib import Path

# Resolve arxiv2md binary (may be in ~/.local/bin, not always on PATH)
_ARXIV2MD = shutil.which("arxiv2md") or str(Path.home() / ".local/bin/arxiv2md")

from openpyxl import load_workbook

BASE_DIR = Path(__file__).resolve().parent
EXCEL_PATH = BASE_DIR / "papers_record.xlsx"
OUTPUT_DIR = BASE_DIR / "markdown_full"
DELETED_IDS_PATH = BASE_DIR / "deleted_ids.txt"
REQUEST_INTERVAL = 3  # seconds between arXiv requests


def load_deleted_ids() -> set[str]:
    if not DELETED_IDS_PATH.exists():
        return set()
    ids = set()
    with open(DELETED_IDS_PATH, encoding="utf-8") as f:
        for line in f:
            sid = line.strip()
            if sid and not sid.startswith("#"):
                ids.add(sid)
    return ids


def load_paper_ids() -> list[str]:
    """Load arxiv_ids from Excel, excluding deleted ones."""
    wb = load_workbook(EXCEL_PATH, read_only=True)
    ws = wb["Papers"]
    header_row = next(ws.iter_rows(min_row=1, max_row=1, values_only=True))
    headers = [str(h) if h is not None else "" for h in header_row]
    try:
        id_col = headers.index("arxiv_id")
    except ValueError:
        print("[ERROR] arxiv_id column not found in Excel")
        sys.exit(1)

    deleted = load_deleted_ids()
    ids = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        sid = str(row[id_col]).strip() if row[id_col] is not None else ""
        if sid and sid not in deleted:
            ids.append(sid)
    return ids


def download_markdown(arxiv_id: str) -> bool:
    """Download full markdown for one paper. Returns True on success."""
    output_path = OUTPUT_DIR / f"{arxiv_id}.md"
    if output_path.exists() and output_path.stat().st_size > 100:
        print(f"  [SKIP] Already exists: {arxiv_id}")
        return True

    try:
        result = subprocess.run(
            [_ARXIV2MD, arxiv_id, "--remove-refs", "--frontmatter", "-o", str(output_path)],
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode != 0:
            stderr = result.stderr.strip()
            # Common errors: paper has no HTML version (pre-2023)
            if "not found" in stderr.lower() or "no html" in stderr.lower() or "404" in stderr:
                print(f"  [SKIP] {arxiv_id}: no HTML version available (pre-2023 paper)")
            else:
                print(f"  [ERROR] {arxiv_id}: {stderr[:120]}")
            # Create empty marker to avoid retrying
            output_path.write_text(f"# {arxiv_id}\n\nHTML version not available on arXiv.\n", encoding="utf-8")
            return False
        size = output_path.stat().st_size
        print(f"  [OK] {arxiv_id}: {size:,} bytes")
        return True
    except subprocess.TimeoutExpired:
        print(f"  [TIMEOUT] {arxiv_id}")
        return False
    except Exception as e:
        print(f"  [ERROR] {arxiv_id}: {e}")
        return False


def build_index(paper_ids: list[str]) -> None:
    """Generate README.md index for full markdown files."""
    links = []
    for sid in paper_ids:
        md_path = OUTPUT_DIR / f"{sid}.md"
        if md_path.exists() and md_path.stat().st_size > 100:
            # Extract title from YAML frontmatter
            text = md_path.read_text(encoding="utf-8")
            title = sid
            for line in text.split("\n"):
                if line.startswith("title:"):
                    title = line.split(":", 1)[1].strip().strip('"')
                    break
            links.append(f"- [{sid}]({sid}.md) — {title[:100]}")

    index = f"""# Agent Memory 论文全文 Markdown

> Generated by arxiv2md | {date.today().isoformat()} | Papers: {len(links)}

{"".join(links)}

---

[在线查看](https://peng-yinghao.github.io/hermes-arxiv-agent/)
"""
    (OUTPUT_DIR / "README.md").write_text(index, encoding="utf-8")
    print(f"[OK] Index written: {len(links)} papers")


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if len(sys.argv) > 1:
        # Single paper mode
        arxiv_id = sys.argv[1]
        download_markdown(arxiv_id)
        return

    # Batch mode
    paper_ids = load_paper_ids()
    print(f"[INFO] {len(paper_ids)} papers to process")

    success = 0
    skipped = 0
    for i, sid in enumerate(paper_ids):
        print(f"[{i+1}/{len(paper_ids)}] {sid}")
        if download_markdown(sid):
            success += 1
        else:
            skipped += 1
        if i < len(paper_ids) - 1:
            time.sleep(REQUEST_INTERVAL)

    build_index(paper_ids)
    print(f"\n[DONE] Success: {success}, Skipped/Error: {skipped}")


if __name__ == "__main__":
    main()
